### ISSUE TITLE
お引っ越しする

### ISSUE THREAD

**Issue by usagi** [usagi/OpenUII#13]
現住所: 札幌市中央区南10条西7丁目 3-8 パークサイドクリスタル 202号室
  ↓
新住所（予定）: 札幌市中央区南6条西26丁目 { 1-1, 1-2 } ミルフィーユ { 506, 502, 206, 202, ?  }号室
- 新居は現在建築中。2月完工予定だったらしいが、3月15日完工予定に遅れているらしい。
- 現地確認次第ではキャンセルして別物件という可能性はある。

準備
- 3月末からの入居が可能…かもしれない。4月からかもしれない。工事や手続きによる。
- 現住居の退去通告: 3月25日（予定）が退去通告の期限として現住居の3月の契約となる見込み
- ざっくり見積もって お家賃3ヶ月分（敷金が2ヶ月分+最初の家賃）+保証会社（予定: 全保連） で4ヶ月分は必要。およそ30万円とみておくのが良さそう。
  - 加えて、引っ越し直後に最小限の家具は欲しいので+10万円みたい。
- 場合によっては入居予約のみして3月31日 火曜日の給与振り込みのあとに支払いとなるようにするのが賢い気がする。（一時的であれ財政難に陥らないために）
  - 現住居の退去期限と新居の入居可能日が微妙に重ならない場合は、現住居を1ヶ月伸ばすよりは友人に段ボール箱を2,3泊預かってもらって、私ビジネスホテルで数日泊まるのが無難かもしれない。

保証会社については不動産屋によると、以下の具合らしい。

> 保証会社に関しましてはリクルートか全保連の２社になります。
> リクルートは初回に月額総支払額（固定費のみ、光熱費は除く）の１００%が契約金として必要です。
> 更新は１年毎で１万円になります。
> 全保連は初回が月額総支払額（固定費のみ、光熱費は除く）の８０%が契約金として必要になります。
> こちらは更新料がないので、初回のみになります。
> この物件で使えるのは２社のみなので、費用面を考慮すると全保連のほうが宜しいかと思われます。

**Comment by usagi** [comment]
クリーチャー問題は寿命を縮めていると思うので「いのち」タグつけといた＠ｗ＠；

**Comment by zakkas783** [comment]
お茶スプラッシュ不可避w

**Comment by usagi** [comment]
現住居のファイナル契約期間が決定: 3月8日から4月7日まで

これなら荷物を一時的に預かってもらったりせずに新居の契約開始と重複するお引っ越し期間を十分にとれそう。

**Comment by usagi** [comment]
現住居の退去に伴う費用は恐らく不要との不動産屋発言。どうやら、入居の際にとられた清掃料6k円は入居ではなく退去の時のための敷金みたいなものだったらしい。

**Comment by usagi** [comment]
お引っ越し手伝ってくれるイケメンズより、水曜とか木曜だと出撃しやすいとの連絡。可能ならそこにスケジュールしよう。

**Comment by usagi** [comment]
3月15日の13時頃に不動産屋へ。新居の見学ができるようになったので、見て決めましょうとのこと。

お給料のタイミングの都合から3/31に支払いをして4/1から入居の契約に持って行きたいところ。

**Comment by usagi** [comment]
4/1から入居予定で不動産屋に投げた。

しかし、どうも私が自営業だと言ったら「入居審査落ちるよあんた」みたいなすんごいやる気のない態度に変わったのでこの不動産屋ダメかもしれない、なにかとらぶったら即切って別の不動産屋に相談行こうかな。

**Comment by usagi** [comment]
訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた訃報: 不動産屋から新居への入居審査お断りされた

**Comment by usagi** [comment]
どうも常口アトムの円山店は信用ならない。使うのやめる。
- 何度か店舗を利用しているが、カウンターで待っている間など、だいたい裏のほうで客を種に若干嫌らしい感じで笑い話にしているふうな会話が漏れ聞こえてくる
- 書いた年収（ボーナス考慮しないで360万って書いたんだけど）と信用調査会社からの連絡で書いてあった事になってた年収が違ってた（460万になってた）
  - zakさんいわく審査通らなかった要因それでは、と。
- 担当の息が臭かった（誰とまでは書かないでおくけど）

**Comment by usagi** [comment]
札幌の不動産はキャラクターがキモいがビッグで探すのが間違いないと思う。

**Comment by usagi** [comment]
札幌市中央区南２条西１２丁目
http://www.kensakun.net/app/detail/3708261

**Comment by usagi** [comment]
札幌市中央区大通西１８丁目
http://www.kensakun.net/app/detail/1037260

**Comment by usagi** [comment]
札幌市中央区北５条西１４丁目
http://www.kensakun.net/app/detail/1352051

ちょっと作りが古臭いけどイオン桑園まで徒歩8分なので何かと困らない。バルコニー広い。最寄り駅がJRになるのでサピカとはお別れでスイカと再開である。別に通勤に使うわけでないのでどうでもよい。

イオン桑園
http://www.aeon.jp/sc/sapporosoen/floor/

**Comment by usagi** [comment]
ビッグに電子メール連絡した。

```
------------------------------------------------------------
□■□■□■□■□■□■　送信内容　■□■□■□■□■□■□
------------------------------------------------------------

■お問い合わせ先■
ビッグ　南１条店　株式会社ビッグシステム
■お問い合わせされたお部屋■
1.お問い合わせ番号：3708261
｜家賃：6.6万円
｜管理費：0.6万円
｜敷金：6.6万円
｜礼金：6.6万円
｜間取：1LDK(34.71㎡)
｜最寄り駅：地下鉄　東西線 西１１丁目 徒歩5分
｜住所：札幌市中央区南２条西１２丁目


■お問い合わせ内容■

ご用件：----------------------------------------------------
物件を内覧したい/物件の詳細を知りたい/入居に関しての相談/条件に合う他の物件を探してほしい
------------------------------------------------------------
ご連絡時間帯：
ご来店希望日：

ご要望・備考：----------------------------------------------
札幌へとりあえず仮住まいを定めて半年、そろそろおおよその地理もわかり、本格的に住まう良い住居を探しております。札幌市内ではたくさんお店を見かけますビッグを使うのが安泰だろうと考え、さしあたり「けんさくん」にてS2W12の良さ気な物件に目星をつけつつも、中央区内の他の物件も含め、先ずはご相談に乗って頂ければ幸いです。

条件など書きましたら「400字以内」とエラーが出たので、ご連絡頂き次第、折り返して追記いたしたいと思います。

なお、ご連絡・平時の相談のやり取りについては緊急性が無い限りは電子メールで頂ければ幸いです。電子メールはいつご連絡を頂いても構いません。よろしくお願いいたします。
------------------------------------------------------------
```

**Comment by usagi** [comment]
その後、条件を伝えて良さ気物件を探してもらったところ、以下のお返事。ビッグよい感じ。

```
お送りする物件について、簡単ですがご説明させて頂きます。
--------------------------------------------------------------------
・クラッセ知事公館前　９０２号室

１１階建ての物件の９階部分のお部屋です。
静かであり、治安の良いと言われている知事公館前周辺エリアに物件がございます。
インターネット使用料無料です。
リビングの向きは西向きです。
キッチンはＩＨです。


・ビッグパレス西線ＥＡＳＴ　６０１号室

９階建ての物件の６階部分のお部屋です。
築年数は経っていますが、建物の造りやエントランスの豪華さでは他の分譲マンショ
ンに負けないグレードの高さを誇ります。
保証人様、契約者様などの申込内容によって家賃が最大３０００円まで値下げ交渉
可能な物件です。
近隣には東光ストアがございます。


・プライムアーバン円山　１００１号室

１０階建ての建物の最上階のお部屋です。
現在は内装・清掃中ですが内覧可能な物件です！
ネット使用料が無料であり、都市ガスシステムキッチン、
大型スーパーの東光ストアまで徒歩５分です。
インターネット使用料が無料の物件です。


・仮）北７条西１２丁目ＭＳ　４０１号室

４階建ての物件の最上階のお部屋です。
向きがわからず申し訳ないのですが、新築であり、内覧可能です。
３月末に完成されるので、４月の頭から入居可能です。
イオン桑園店まで徒歩７分です。
桑園エリアは中心部よりも街の雰囲気が落ち着いており、築浅の物件も多く
街が綺麗な印象を受けるエリアです。

・ラトゥール　１４０３号室

管理費を含めた月額がかなりオーバーしてしますのですが、最上階であり南向き、
円山クラスまで徒歩１０分、地下鉄東西線「西１８丁目」駅まで徒歩２分と好条件
が揃った物件なのでご提案させて頂きました。
３月３１日退去予定の物件であり、４月１日から内覧可能です。
家賃が２０００円低い６０３号室も同じタイミングでご紹介可能です。

・ミルフィーユ
５階建ての物件の最上階のお部屋です。
物件の設備や内装から見て、場所以外はレジデンス大通公園と似ている物件です。
他にも空き号室が沢山あり、今の段階だと選べる物件です。
内覧可能です。
------------------------------------------------------------------------
```

**Comment by usagi** [comment]
とりあえずこのチケットは一旦閉じて、新規にビッグでの引っ越し検討チケット建てよう。
