### ISSUE TITLE
「札幌⇔金沢」の往復についてより良い旅路を考える

### ISSUE THREAD

**Issue by usagi** [usagi/OpenUII#6]
仕事の都合、自宅のある札幌市中央区から業務先の石川県金沢市へ出張する機会が発生している。安直にAIRDOの新千歳⇔小松の往復航空券をベースに旅路と宿を設計したが、トータル75k円という大型出費になってしまう事が判明している。

AIRDOでは新千歳から小松へ21時少し前に着き、逆は8時台に出発という1便/日の状態で2泊3日となることも宿代に影響している。

現状の次回出張時の旅行計画は次の通り。

``` tsv
2015/03/12  木曜日   16:30   自宅  発/徒歩  
2015/03/12  木曜日   16:39   札幌市営地下鉄/南北線/中島公園駅 着 
2015/03/12  木曜日   16:44   札幌市営地下鉄/南北線/中島公園駅 発/鉄道  200
2015/03/12  木曜日   16:49   札幌市営地下鉄/南北線/札幌駅   着 
2015/03/12  木曜日   16:49   札幌市営地下鉄/南北線/札幌駅   発/徒歩  
2015/03/12  木曜日   16:55   JR/札幌駅    着 
2015/03/12  木曜日   17:10   JR/札幌駅/エアポート170号  発/鉄道  ¥1,070
2015/03/12  木曜日   17:47   新千歳空港 着 
2015/03/12  木曜日   18:30   新千歳空港 発/航空  ¥31,400
2015/03/12  木曜日   20:15   小松空港    着 
2015/03/12  木曜日   20:25   小松空港/路線バス乗降口/2:市内経由金沢駅ゆき    発/バス  ¥1,130
2015/03/12  木曜日   21:12   バス停/新神田(北國銀行前)    着 
2015/03/12  木曜日   21:12   バス停/新神田(北國銀行前)    発/徒歩  
2015/03/12  木曜日   21:15   ホテルレマン  着/宿泊  ¥3,800

2015/03/13  金曜日   --:--          （仕事）
2015/03/13  金曜日   18:18   ホテルレマン  着/宿泊  ¥3,800

2015/03/14  土曜日   6:30    ホテルレマン  発/徒歩  
2015/03/14  土曜日   6:33    バス停/新神田(北國銀行前)    着 
2015/03/14  土曜日   6:47    バス停/新神田(北國銀行前)    発/バス  ¥1,130
2015/03/14  土曜日   7:36    小松空港    着 
2015/03/14  土曜日   8:20    小松空港    発/航空  ¥31,400
2015/03/14  土曜日   9:55    新千歳空港 着 
2015/03/14  土曜日   10:03   新千歳空港/エアポート101号   発/鉄道  ¥1,070
2015/03/14  土曜日   10:40   JR/札幌駅    着 
2015/03/14  土曜日   10:40   JR/札幌駅    発/徒歩  
2015/03/14  土曜日   10:46   札幌市営地下鉄/南北線/札幌駅   着 
2015/03/14  土曜日   10:49   札幌市営地下鉄/南北線/札幌駅   発/鉄道  ¥200
2015/03/14  土曜日   10:54   札幌市営地下鉄/南北線/中島公園駅 着 
2015/03/14  土曜日   10:54   札幌市営地下鉄/南北線/中島公園駅 発/徒歩  
2015/03/14  土曜日   11:03   自宅  着 
```
- JRエアポートxxx号: http://www.jrhokkaido.co.jp/network/airport/index.html
- ホテルレマン: http://hotel-reman.com/

これに対し、zakさんから「デカイ空港+陸路」という提案を得た:
https://twitter.com/USAGI_WRP/status/569892793776099330

**Comment by usagi** [comment]
書き忘れた: Total cost ¥75,200

**Comment by zakkas783** [comment]
* <2015-03-12 木 16:30> 自宅→ | (徒歩) 0
* <2015-03-12 木 16:39> →中島公園
* <2015-03-12 木 10:23> 中島公園→ | (札幌市営地下鉄南北線) 200
* <2015-03-12 木 10:28> →札幌
* <2015-03-12 木 10:35> 札幌→ | (エアポート104号) 1070
* <2015-03-12 木 11:17> →新千歳
* <2015-03-12 木 12:10> 新千歳→ | (JetStar) 5890
* <2015-03-12 木 14:30> →関空
* <2015-03-12 木 14:35> 関空→ | (ラピートβ50号) 920+510
* <2015-03-12 木 15:10> →新今宮
* <2015-03-12 木 15:15> 新今宮→ | (ＪＲ大阪環状線)
* <2015-03-12 木 15:32> →大阪
* <2015-03-12 木 15:42> 大阪→ | (特急サンダーバード27号) 4750+2380
* <2015-03-12 木 18:21> →金沢
* <2015-03-12 木 18:25> 金沢→ | (徒歩) 0
* <2015-03-12 木 18:45> →ホテルレマン | 3800

* <2015-03-13 金 18:00> →ホテルレマン | 3800

* <2015-03-14 土 06:30> ホテルレマン→ | (徒歩) 0
* <2015-03-14 土 06:50> →金沢
* <2015-03-14 土 07:02> 金沢→ | (特急サンダーバード6号) 5840+2380
* <2015-03-14 土 09:34> →新大阪
* <2015-03-14 土 09:46> 新大阪→ | (特急はるか15号) 0+970
* <2015-03-14 土 10:34> →関空
* <2015-03-14 土 15:55> 関空→ | (JetStar) 5190
* <2015-03-14 土 17:50> →新千歳
* <2015-03-14 土 18:03> 新千歳→ | (エアポート181号) 1070
* <2015-03-14 土 18:40> →札幌
* <2015-03-14 土 18:50> 札幌→ | (札幌市営地下鉄南北線) 200
* <2015-03-14 土 18:55> →中島公園

**Comment by zakkas783** [comment]
- 2015-03-12 木 10:23 中島公園→ | (札幌市営地下鉄南北線) 200
- 2015-03-12 木 10:28 →札幌
- 2015-03-12 木 10:35 札幌→ | (エアポート104号) 1070
- 2015-03-12 木 11:17 →新千歳
- 2015-03-12 木 12:10 新千歳→ | (JetStar) 5890
- 2015-03-12 木 14:30 →関空
- 2015-03-12 木 14:35 関空→ | (ラピートβ50号) 920+510
- 2015-03-12 木 15:10 →新今宮
- 2015-03-12 木 15:15 新今宮→ | (ＪＲ大阪環状線)
- 2015-03-12 木 15:32 →大阪
- 2015-03-12 木 15:42 大阪→ | (特急サンダーバード27号) 4750+2380
- 2015-03-12 木 18:21 →金沢
- 2015-03-12 木 18:25 金沢→ | (徒歩) 0
- 2015-03-12 木 18:45 →ホテルレマン | 3800
- 2015-03-13 金 18:00 →ホテルレマン | 3800
- 2015-03-14 土 06:30 ホテルレマン→ | (徒歩) 0
- 2015-03-14 土 06:50 →金沢
- 2015-03-14 土 07:02 金沢→ | (特急サンダーバード6号) 5840+2380
- 2015-03-14 土 09:34 →新大阪
- 2015-03-14 土 09:46 新大阪→ | (特急はるか15号) 0+970
- 2015-03-14 土 10:34 →関空
- 2015-03-14 土 15:55 関空→ | (JetStar) 5190
- 2015-03-14 土 17:50 →新千歳
- 2015-03-14 土 18:03 新千歳→ | (エアポート181号) 1070
- 2015-03-14 土 18:40 →札幌
- 2015-03-14 土 18:50 札幌→ | (札幌市営地下鉄南北線) 200
- 2015-03-14 土 18:55 →中島公園

**Comment by usagi** [comment]
@zakkas783 ありがとうございます！お引っ越し資金温存のためにさっそくプラン変更処理始めたいと思います。

**Comment by usagi** [comment]
JetStar、アホ安いだけのリスクが高い事がちょっと調べて感じられてためらっている。

**Comment by zakkas783** [comment]
http://www.jalan.net/dp/ana/ua/uap3200/uaw3201.do?reShFlg=1&searchModeTab=1&outwardBoardYear=2015&outwardBoardMonth=3&outwardBoardDay=12&outwardDepAptCd=SPK&outwardArrAptCd=KMQ&outwardFlightNo=ADN-4824-L&outwardFlightNoLabel=4824&homewardBoardYear=2015&homewardBoardMonth=3&homewardBoardDay=14&homewardDepAptCd=KMQ&homewardArrAptCd=SPK&homewardFlightNo=ADN-4825-L&homewardFlightNoLabel=4825&searchPanelOpen=0&stayCount=2&roomCount=1&adultNum=1&stayDay=12&afCd=AJ&kenCd=190000&lrgCd=192000&activeSort=0&stayYear=2015&stayMonth=3&distCd=01&careNsmr=1&minPrice=0&maxPrice=999999&screenId=UAW1402&yadNo=322566&planCd=00438836&roomTypeCd=0017976&viaList=1&reShPlanList=&rentacar=&carTypeCd=&cdwFlg=&dpOptionIds=

airdo(/ana)新千歳→小松ルートを取るプランをじゃらんで探してみました。往復チケット、二泊込みで43100en。
だいたいの場合、じゃらんとかHISとかJTBといった旅行会社が往復のチケットをはやめに押さえているし、ホテルと提携しているので、ふつうに航空券と宿探すよりものすごく安くなります。

// ホテルの場所や都合がわるければ一泊にして_ホテルは捨てる_、という選択もアリ。

**Comment by usagi** [comment]
なんだそれ迷惑な。

**Comment by usagi** [comment]
飛行機ほとんど埋まってたの「じゃらん」のせいか。「じゃらん」死ぬべき。

**Comment by usagi** [comment]
禁煙部屋埋まってたのも「じゃらん」のせいか。「じゃらん」死ね。

**Comment by zakkas783** [comment]
あ、そのへん(3/14近辺)で部屋が埋まっているのは北陸新幹線のせいだと思います。

**Comment by usagi** [comment]
まるでまったくいみわからないけど北陸新幹線も死になさいよ！

**Comment by usagi** [comment]
AIRDO キャンセルの手数料。出発前。

> 北海道発往復運賃  適用なし

http://airdo.jp/reservation/cancel/index.html

**Comment by usagi** [comment]
じゃらんで 航空機＋宿 取得完了。

![ss0281](https://cloud.githubusercontent.com/assets/115972/6364484/f4ecad98-bce9-11e4-927a-a56d7b401374.png)

**Comment by usagi** [comment]
このあと必要な作業をチケット化してこのチケットはクローズします。
- キャンセル: AIRDO
- キャンセル: ホテルレマン
- 航空機の新チケット（ANA）の搭乗手続き用のデータのDropBoxへの配置
- 旅行工程の詳細設計の書き直し
